# Generated by Django 4.2.4 on 2023-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
